String first_page(){
  String ptr = "<!DOCTYPE HTML>";
ptr+="<html>";
ptr+="<head> <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
ptr+="<style>";
ptr+="input[type=submit] {width: 15;background-color: blue;color: white;padding: 14px 50px;margin: 8px 0;border: 1px solid DarkSlateGray;border-radius: 50px;cursor: pointer;}";
ptr+="</style>";
ptr+="</head>";
ptr+="<body bgcolor = \"lightgrey\">";
ptr+="<center><h1>Configuration Menu</h1><br><br>SSID: &nbsp;";
ptr+= STA_ssid;
ptr+="&nbsp&nbsp&nbsp&nbspPassword: &nbsp;";
ptr+= STA_password;
ptr+="<br>";
ptr+="<form action=\"/ConfigureWiFi\">";
ptr+=    "<input type=\"submit\" value=\"Configure Wi-Fi\">";
ptr+="</form><br><br>";
ptr+="API: &nbsp;";
ptr+= SN_node_api;
ptr+="<br>";
ptr+="<form action=\"/ConfigureAPI\">";
ptr+=   " <input type=\"submit\" value=\"Configure API\">";
ptr+="</form><br><br>";
ptr+="Machine Name: &nbsp;";
ptr+= MachineName;
ptr+="<br>";
ptr+="<form action=\"/ConfigureMachineName\">";
ptr+=    "<input type=\"submit\" value=\"Configure Machine name\">";
ptr+="</form><br><br>";
ptr+="Project Code: &nbsp;";
ptr+= Project_Code;
ptr+="<br>";
ptr+="<form action=\"/ConfigureProject_Code\" >";
ptr+=    "<input type=\"submit\" value=\"Configure Project Code\">";
ptr+="</form><br><br>";
ptr+="Input1: &nbsp";
ptr+= Input1;
ptr+=" &nbsp;&nbsp;&nbspInput2: &nbsp";
ptr+= Input2;
ptr+=" &nbsp;&nbsp;&nbspInput3: &nbsp";
ptr+= Input3;
ptr+=" &nbsp;&nbsp;&nbspInput4: &nbsp";
ptr+= Input4;
ptr+="<br><br>Input5: &nbsp";
ptr+= Input5;
ptr+=" &nbsp;&nbsp;&nbspInput6: &nbsp";
ptr+= Input6;
ptr+=" &nbsp;&nbsp;&nbspInput7: &nbsp";
ptr+= Input7;
ptr+=" &nbsp;&nbsp;&nbspInput8: &nbsp";
ptr+= Input8;
ptr+="<br><form action=\"/ConfigureInputs\" >";
ptr+=    "<input type=\"submit\" value=\"Configure Inputs\">";
ptr+="</form><br><br>";
ptr+="<form action=\"/close\" >";
ptr+=    "<input type=\"submit\" value=\"Close\">";
ptr+="</form><br><br></html>";
return ptr;
}
